### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by q1085909155** [artvin01/TF2-Zombie-Riot#2]
When I finish all dependencies, run the server appeared the situation, what should I do?
![image](https://user-images.githubusercontent.com/69096633/170856015-7271e26a-7bbe-4d98-a3f8-d16c72edd880.png)

**Comment by artvin01** [comment]
You didnt get all the depencencies.
Lamba is required.

**Comment by q1085909155** [comment]
Oh sorry, there are so many dependencies that I forgot to put the compiled plug-in into my server. He's up and running now, thank you

**Comment by q1085909155** [comment]
Now I have a new problem, the bot doesn't move and it sends me spam

**Comment by q1085909155** [comment]
![image](https://user-images.githubusercontent.com/69096633/170856953-d134fc3c-f8d8-43b8-b570-459b9dd9ff8c.png)

**Comment by artvin01** [comment]
Do you have the navmesh?

**Comment by q1085909155** [comment]
Sorry, what is a navmesh

**Comment by artvin01** [comment]
![image](https://user-images.githubusercontent.com/76885107/170857592-d68ac185-116b-4474-9107-a308a7ddf4fa.png)
Put both off these files in your maps folder, that .nav file is a must as it tells the npcs how to get where

**Comment by q1085909155** [comment]
Yes, I've put them together

**Comment by artvin01** [comment]
Ok i will go search myself on why it doesnt work, ill make a clean install and get back to you, maybe i missed something

**Comment by q1085909155** [comment]
Well, thank you for your help and look forward to your recovery

**Comment by artvin01** [comment]
Oh and that spam might be because of some setting you have where you enabled debug in collisionhook, or its a listen server, im not sure.

**Comment by q1085909155** [comment]
Sorry, this is not working, I should try to reinstall your plug-in

**Comment by artvin01** [comment]
Ill check again, reinstalling wont fix it i think

**Comment by q1085909155** [comment]
I may have had some problems installing some of the dependencies, so I tried a proper re-installation

**Comment by artvin01** [comment]
Good news, i was able to recrate the issue of where zombies dont move, i will look into why now

**Comment by artvin01** [comment]
I have found the reason why, some gamedata is oudated, i will now look which it is and put it on my github

**Comment by q1085909155** [comment]
Too bad my solution didn't work. This is a great plugin

**Comment by q1085909155** [comment]
I look forward to your fixes when I help translate more grammar

**Comment by artvin01** [comment]
I have found a fix, i send the updated gamedata to the repository, you can for now have the updated one here right now
[PathFollower.txt](https://github.com/artvin01/TF2-Zombie-Riot/files/8792922/PathFollower.txt)

**Comment by q1085909155** [comment]
You successfully repaired him, thank you very much, and now they're moving

**Comment by artvin01** [comment]
no problem

**Comment by q1085909155** [comment]
I want to know then about this kind of notification, he makes me blind to my chat box
CH_PassFilter: ent1: 168, ent2: 92
CH_PassFilter: ent1: 168, ent2: 1
CH_PassFilter: ent1: 168, ent2: 1
CH_PassFilter: ent1: 168, ent2: 1
CH_PassFilter: ent1: 168, ent2: 1
CH_PassFilter: ent1: 168, ent2: 1
CH_PassFilter: ent1: 168, ent2: 1
CH_PassFilter: ent1: 168, ent2: 1
CH_PassFilter: ent1: 168, ent2: 1
CH_PassFilter: ent1: 168, ent2: 1

**Comment by artvin01** [comment]
I never had this, you must have something that does this or some cvar that enables this, its not there by default. if you host a server seperatly.

**Comment by q1085909155** [comment]
There's nothing I can do to shut it down? I don't even know which plugin it came fro
![屏幕截图(42)](https://user-images.githubusercontent.com/69096633/170861173-f0ca199c-0766-43e0-ae4b-2f64d1a21830.png)
m

**Comment by q1085909155** [comment]
I found it. The collisionhook_test plugin is at fault
![image](https://user-images.githubusercontent.com/69096633/170861279-242e293f-b6dd-4454-bc3c-6be10e338570.png)

**Comment by artvin01** [comment]
Ill concider this done so ill close it
