### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by Shacoree** [artvin01/TF2-Zombie-Riot#223]
From where can i get more zr maps? This mod is amazing!

**Comment by artvin01** [comment]
I only gave an example map, i want server hosters to make their own maps so several servers arent just a copy of one another mapwise

**Comment by Shacoree** [comment]
but there are configs for multiple maps in the plugin

**Comment by Shacoree** [comment]
11 in total, only one of which has it's bsp file

**Comment by artvin01** [comment]
its just a config file, i will not provide the maps.
I concider this closed now.

**Comment by MichaelRevin** [comment]
@Shacoree 
https://github.com/MichaelRevin/TF2-ZombieRiot-Maps

**Comment by artvin01** [comment]
Thats stealing as i didnt permit this and neither was i asked for permission.
I will not assist you two in any further debugging or gamemode problems.
