### ISSUE TITLE
Slandering bastards

### ISSUE THREAD

**Issue by MichaelRevin** [artvin01/TF2-Zombie-Riot#224]
You take gamemode from counter strike source, release maps and call it stealing when other communtiies try to make it easier to host it. Go eat a boot. Read Valve Terms Of Use and if you don't like it, don't release anything for game and engine you don't own and the license you don't follow. Sigh.
https://store.steampowered.com/subscriber_agreement/#5
https://partner.steamgames.com/doc/sdk/uploading/distributing_source_engine
https://developer.valvesoftware.com/wiki/Valve_Developer_Community:Terms_of_Use
I will be filling report with github for slander and disrespect.

**Comment by artvin01** [comment]
I dont remember telling you to delete it or do anything, i just have my own morals and refuse to help such people. Im not forced to do anything for anyone.

I also didnt take anything from css.
gmod actually if you read the credits, of which i did credit the original makers of the music from gmod ZS but thats the about the only thing.

Your arguments are invalid and your need to insult me and my team just solidifies this.

**Comment by artvin01** [comment]
I also made my own maps, have had my own community make maps or heavily edited existing maps and asked for permission if avaiable, of which credits, if they existed i havent deleted either.

Also this is not an issue, thank you.
