### ISSUE TITLE
new question

### ISSUE THREAD

**Issue by q1085909155** [artvin01/TF2-Zombie-Riot#3]
After I played with the player for a while, the server crashed.
Also, I have zr_infinitecash set to 0, why am I and my players 999999

**Comment by q1085909155** [comment]
Ok, now the problem of 99999 has been solved. I still have to observe the crash situation. Please wait for more information from me

**Comment by artvin01** [comment]
Cant do anything without you giving me a crashlog

**Comment by q1085909155** [comment]
Oh, I was going to give it to you. I forgot it
![屏幕截图(44)](https://user-images.githubusercontent.com/69096633/170864969-24f8ccd9-64f1-473d-8aef-2f928a2c9bb9.png)

**Comment by artvin01** [comment]
that isnt a crashlog, thats just something noted down in the errorlog

im also sure that you have some other plugins causing the crash as i never had any random crash after some time in this gamemode, make sure that nothing is conflicting

also install accelerator crash logger otherwise i cant do anything

**Comment by q1085909155** [comment]
Sorry, I haven't found any information about the crash. At present, I'm still trying to find out what caused the crash. The current situation is good and there is no sign of crash. So far my list of plug-ins is clean, with only dependencies installed
![屏幕截图(46)](https://user-images.githubusercontent.com/69096633/170865202-174e2c46-2ccd-434b-aa7a-8f0818d36b9f.png)

**Comment by artvin01** [comment]
I need the crashlog now, nothing is off from what it looks like, i cant help otherwise

**Comment by q1085909155** [comment]
I'd also like to provide you with my crash log. But my journal doesn't record anything
The crash time is 2022/5/29 18:37:44 and 2022/5/29 18:32:23 respectively
[L20220529.log](https://github.com/artvin01/TF2-Zombie-Riot/files/8793207/L20220529.log)

**Comment by artvin01** [comment]
.... You enabled no special zombies, disable it as you dont have the models and arent allowed to use them unless you ask the moddeler.

**Comment by q1085909155** [comment]
Is that what caused my breakdown?

**Comment by artvin01** [comment]
yes

**Comment by artvin01** [comment]
and you also ignored the warning i gave in the readme, uncool

**Comment by artvin01** [comment]
i wont provide further assistance due to this, youre on your own as you ignored what was said there.

**Comment by q1085909155** [comment]
I'm sorry, my English is not good

**Comment by artvin01** [comment]
Do what i said and itll work again, i will be closing this now

**Comment by q1085909155** [comment]
For now, I just want the plugin to work properly, and then I will study your instructions carefully. I'm sorry. I'll read all the instructions carefully
