### ISSUE TITLE
More voice

### ISSUE THREAD

**Issue by q1085909155** [artvin01/TF2-Zombie-Riot#4]
I apologize for my reckless behavior earlier, my man. I'm trying to get permission from Mr. Crusty, but he doesn't seem to be online right now. 

My players and I love your plugin, and we all want you to update the menu translation and provide more Commands and cvar's, and I appreciate that.

I think you should change the comment about Cvar: zr_nospecial. Otherwise you may have more players with poor English coming to you in the future. I apologize to you again for my poor English, and I hope you can forgive me.
![屏幕截图(51)](https://user-images.githubusercontent.com/69096633/170870315-bf4afe65-f970-4690-b10d-05a771985f2b.png)

**Comment by q1085909155** [comment]
Update Commands and cvar's
Such as:
Administrators can give points to players
Killing zombies earns you points
Pop-ups will now pop up over a teammate's head when he or she is down

**Comment by artvin01** [comment]
The default is 1 for that cvar

Points are given though damage, healing and other things, not killing

If you mean creditsthrn they are only given on found end or globally if a zombie dies if its enabled, otherwise only 3 people will have all the money
I didnt add a command for admins giving credits as it was never needed and just promoted begging admins for money

If hedoesnt give you permission then just leave the cvar on 1, the gamemode is fine without it and doesnt break

May i ask for the ip?

**Comment by artvin01** [comment]
I had a popup but removed it as it wasnt obvious at all, its an outline when a teammate is down now

**Comment by artvin01** [comment]
I had a popup but removed it as it wasnt obvious at all, its an outline when a teammate is down now

**Comment by q1085909155** [comment]
47.100.226.218:27015

**Comment by artvin01** [comment]
I can add your ip to the list of servers i have here in the github who have my gamemode if you want

I also have to add every text the plugin has to translations later on so you can translate it, but i have been quite tired or working daily so ill do it later

Oh yeah, if you want a zombie to give money use "cash" "15" on the wave for a zombie like in the raid config, that will mak that zombie give 15 cash to everyone when it dies

**Comment by q1085909155** [comment]
Sure, it's my pleasure, man. It's a Chinese server

**Comment by artvin01** [comment]
If you mind, later on can you pull request the chinese translations here once i added all text to it? I'd like to have alot of languges supported

**Comment by artvin01** [comment]
As i still miss tinyfew

**Comment by q1085909155** [comment]
Of course, but my translation is not perfect, and he can only translate the name of the weapon locally

**Comment by artvin01** [comment]
Translate as much as you want, just pull request it once done

I now added translations to almost everything including zombie names

**Comment by artvin01** [comment]
You may now translate everything.

**Comment by q1085909155** [comment]
Ok, I saw it when you posted it, but I have to go to bed now, it's nearly 1am here

**Comment by q1085909155** [comment]
There seems to be some glitch in the translation

![屏幕截图(53)](https://user-images.githubusercontent.com/69096633/170913332-a7d27150-9598-4cba-99e6-998c89da0450.png)

It overburdened my server

**Comment by q1085909155** [comment]
When you meet Bob
![屏幕截图(55)](https://user-images.githubusercontent.com/69096633/170917141-3b9dc612-2b3f-4a03-9c9a-82706c159ada.png)

**Comment by artvin01** [comment]
Gonna check now

**Comment by artvin01** [comment]
Should be fixed now

**Comment by artvin01** [comment]
Get translation files and the plugin itself

**Comment by q1085909155** [comment]
OK, but I will try again later because there are players playing on my server

**Comment by q1085909155** [comment]
You can add a command that allows the administrator to give credit to the player

**Comment by artvin01** [comment]
Why is that needed

**Comment by q1085909155** [comment]
Because it adds a lot of entertainment and allows me to test more things :)

**Comment by artvin01** [comment]
fair, give me a sec

**Comment by artvin01** [comment]
![image](https://user-images.githubusercontent.com/76885107/170967851-683c0e73-f6fd-4382-b389-232bdd2e69e7.png)
sm_give_cash artvin -500
or to give money
sm_give_cash artvin 500

**Comment by artvin01** [comment]
There is no translation for it as its just a cheat command

**Comment by artvin01** [comment]
Ill close this how, open new issues if you have any, otherwise contact me on discord or steam.
