### ISSUE TITLE
What should I do next

### ISSUE THREAD

**Issue by q1085909155** [artvin01/TF2-Zombie-Riot#5]
Hey Artvin, I've got Permission from Mr. Crusty, now I can use the model, do I just need to set zr_nospecial to 0? This won't crash my server, will it? I realized I was missing some models, like Buildable Mortar

**Comment by q1085909155** [comment]
But I'm going to stick with the error model

**Comment by q1085909155** [comment]
![屏幕截图(57)](https://user-images.githubusercontent.com/69096633/171009573-448b1f2d-2946-4349-9211-1beb65000124.png)

It still displays error

**Comment by q1085909155** [comment]
Have you uploaded the complete model to Github

**Comment by artvin01** [comment]
The custom sentry model is already in the github, you didnt get it

**Comment by artvin01** [comment]
Nvm i see it now

**Comment by q1085909155** [comment]
ok

**Comment by q1085909155** [comment]
Oh, I'm glad you found a translation error. I was just going to inform you.
I passed the test just now, but I still don't have the model
![屏幕截图(59)](https://user-images.githubusercontent.com/69096633/171031294-802828c1-6a57-4115-b1e0-15e5f3054d67.png)

and Buildable Mortar
![屏幕截图(57)](https://user-images.githubusercontent.com/69096633/171031313-2d18e434-4f0b-4d5f-91a2-3012a21069bc.png)

**Comment by artvin01** [comment]
You need to ask crusty for the model files too

I dont know why the mortar doesnt show, thr model is the one i put in, check if you download it even

**Comment by q1085909155** [comment]
When I looked at it the next day, it was showing normally

**Comment by q1085909155** [comment]
Where can I get more maps that support your plugin

**Comment by artvin01** [comment]
Usually self made maps, there arent many but my own community made them for me often

**Comment by artvin01** [comment]
I gave 1 map as an example in the github to show how a map would work

**Comment by q1085909155** [comment]
Sorry, I can't make maps, can I get more maps from you?

**Comment by artvin01** [comment]
Add me on steam, i can there

**Comment by q1085909155** [comment]
applied
