### ISSUE TITLE
[crash report] player death causes an crash

### ISSUE THREAD

**Issue by StShAzzy** [artvin01/TF2-Zombie-Riot#52]
https://crash.limetech.org/sr434ydwbjdm
https://crash.limetech.org/adnxxxtroxvq (suicided)

attempted on version 1.11.0.6911
also attempted with the same version this server is running (74.91.119.154:27017)

extra context:
for some unknown reason, and i promise you, unknown, i already tried running it with an clean installation and still crashed, i got no clue on what might be happening, the crash can be replicated just by dying at any moment, or pressing your killbind, which produces a different crash, in case any more info is required please contact me at: Raphtalia Dreemurr#1832

**Comment by artvin01** [comment]
I had this but before but it fixed itself so i cant replicate it, try to reload the plugin once the server started, see if that fixes it, i will later once im not sick look into the crash logs and see what i can do

**Comment by artvin01** [comment]
You cursed me, now it happens again on my server
atleast i can now figure out whats going on

**Comment by artvin01** [comment]
I found the fix, the dhook
//	DHook_CreateDetour(gamedata, "CTFPlayer::DropAmmoPack", DHook_DropAmmoPackPre);
Caused it
I have just removed it and placed a hook that deleetes any ammo packs from anywhere instead

So your issue is fixed, ill be closing it with this!
