### ISSUE TITLE
Alot of translations seem to be broken (on the plugin side)

### ISSUE THREAD

**Issue by StShAzzy** [artvin01/TF2-Zombie-Riot#82]
L 11/09/2022 - 22:34:25: [SM] Exception reported: Language phrase "Bob the Overgod of gods and destroyer of multiverses" not found (arg 5)
L 11/09/2022 - 22:34:25: [SM] Blaming: disabled\zombie_riot.smx
L 11/09/2022 - 22:34:25: [SM] Call stack trace:
L 11/09/2022 - 22:34:25: [SM]   [0] ShowSyncHudText
L 11/09/2022 - 22:34:25: [SM]   [1] Line 1675, zombie_riot\npcs.sp::Calculate_And_Display_hp
L 11/09/2022 - 22:34:25: [SM]   [2] Line 1522, zombie_riot\npcs.sp::NPC_OnTakeDamage_Post
there's also this
![image](https://user-images.githubusercontent.com/90798128/200978890-704ebeb6-adc3-43b9-a3cd-fddedc91efd1.png)
menu not fully translated despite the file being translated

**Comment by artvin01** [comment]
Did this happen with the latest pull?

**Comment by artvin01** [comment]
I cant seem to recreate your issue, try to update your plugin, gamedata, and translations

**Comment by StShAzzy** [comment]
i downloaded about a hour ago the entire repo and compiled the plugin to update my server...

**Comment by artvin01** [comment]
I have found the issue,  there was a missing " in one of the translation files, im sorry for this.

**Comment by artvin01** [comment]
I will fix it and push a fix

**Comment by StShAzzy** [comment]
oh.

**Comment by artvin01** [comment]
Fixed now, again sorry for this, other people translate it and often miss some "" which mess up the plugin.

**Comment by StShAzzy** [comment]
this reminds me that i have an translation error on 'Bob the Overgod of gods and destroyer of multiverses'

**Comment by StShAzzy** [comment]
there's also this 
https://github.com/artvin01/TF2-Zombie-Riot/blob/main/addons/sourcemod/translations/zombieriot.phrases.zombienames.txt#L85

can you also replace the line 585 on zombienames.txt ("pt"		"Bob o Poderoso e destruir de multiversos") for "pt"		"Bob o todo poderoso destruidor de multiversos"

**Comment by artvin01** [comment]
That should be fixed with this, if not, then i will investigate later as it is late currently, but as far as i know youre never supposed to see that name anyways.

**Comment by artvin01** [comment]
Will do later
